liip_imagine:
    filter_sets:
        logo:
            quality: 75
            filters:
                thumbnail:
                    size: [150, 150]
                    mode: outbound
        thumb:
            quality: 75
            filters:
                thumbnail:
                    size: [360, 230]
                    mode: outbound
        medium:
            quality: 75
            filters:
                thumbnail:
                    size: [800, 530]
                    mode: outbound
